apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  CLERK_SECRET_KEY: c2tfdGVzdF9NMDFoVXRTR2hMb2ZoUXBmZGJ5MGdHVFk2ajA2QWExU3BKdUMzSFZuQQ==
  DATABASE_URL: bXlzcWw6Ly9sdWlzNDg2OlBhc3N3b3JkMUBteXNxbDozMzA2L2Vjb21tZXJjZV9kYg==
  STRIPE_API_KEY: c2tfdGVzdF81MU96b1hpSkh5MlFtRTFMdzZhV0ZaV2hrQ2tUMk9kbTdqcGpjcjJSc3JrVGJsYVBxZDBROGIyVkFOWlNhOENhbTg4NjBhNjVWQUhnS0JGclh0R0JPSk02MDB3YjY3cmI4cw==
  STRIPE_WEBHOOK_SECRET: d2hzZWMvZDc4YjgzNDQxZGQ4OTIwM2RiNTMyYmZjY2Q2YTA0ZTk0ZDQ3M2VmYjVmNGJjY2E0NTY3MmNiMmRmYmMyNTFh