apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  CLERK_SECRET_KEY: sk_test_M41hUtSCghLofhQpfdby0kGTY6j06Aa1SpJuC3HVnA
  DATABASE_URL: mysql://luis486:Password1.@mysql:3306/ecommerce_db
  STRIPE_API_KEY: sk_test_51OzoXiJHy2QmE1Lw6aWFZWhkCkT2Odm7jpjcr2RsrkTblahPqd0Q8b2VANZSa8Cam8860A65VAHgkBFrXtGBOJO600wb67rb8s
  STRIPE_WEBHOOK_SECRET: whsec_d78b83441dd891931db532bfccd6a04e94d473efb5f4bcca45672cb2dfbc251a